### PR TITLE
Display both absolute frequencies and percentages

### PR DESCRIPTION
**Pull request by maziello**
Closes #77

Added option to display both the absolute frequency and the percentage of the total for each intersection and category.
Refactored the string formatting using .format() instead of %

### CODE REVIEW

**Comment by jnothman** [comment]
Thanks for the pull request. @arosenfeld addressees the same issue in #77. Unfortunately I've not found the time and focus to touch that up and merge it. There were some tricky questions of consistency there. I would appreciate if you took a look at that pull request and compare how it handles this matter.

**Comment by maziello** [comment]
Thanks for the quick response. I have looked into issue [#77](https://github.com/jnothman/UpSetPlot/pull/77) and I like the idea of adding a new parameter. I think show_counts and show_percents should not affect each other. What I mean is we can still keep the flexibility of the current show_counts implementation and display percentages on top of it.
I hope the examples below help:
Default plots have no labels:
```python
import upsetplot
 
example = upsetplot.generate_counts()
plot(example, show_counts=False, show_percents=False)
```
upset_no_labels

Percentages can be displayed even with no counts:
```python
plot(example, show_counts=False, show_percents=True)
```
upset_percents_only

When counts and percentages are displayed, percentages are in a new line below:
```python
plot(example, show_counts=True, show_percents=True)
```
upset_percents_counts

This strategy keeps the current formatting functionality of show_counts, with or without displaying percentages:
```python
plot(example, show_counts='%.2f', show_percents=True)
```
upset_percents_counts_floats

The change only affects the label generation, adding the new parameter and doesn't break any existing implementation.
What do you think?

**Comment by jnothman** [comment]
Sorry I've been relatively short of time lately or I would probably have
tweaked and merged @arosenfeld's PR months ago. I hope I can get to this
over March.

**Comment by jnothman** [comment]
Hi @maziello, I've tried to refactor this and add some tests. WDYT?

**Comment by jnothman** [comment]
Hi @arosenfeld, in the end i'm inclining to adopt this version. Let me know your thoughts.

**Comment by arosenfeld** [comment]
Hi @jnothman, I haven't had a chance to look at the code itself from @maziello, but the plots themselves look great.  Go for it!

**Comment by maziello** [comment]
Hi @jnothman, it looks great. Go for it!
Thanks a lot for looking into this!!!

**Comment by jnothman** [comment]
Thank you @maziello and @arosenfeld!x

**Pull request merged**
