### PR TITLE
Parameters to control colours etc.

### LINKED ISSUE #46: colour by column
Hey there, I really like your implementation of the upset plot and would like to use it in a publication.

I was wondering if you had plans to introduce colour coding? i.e. allow us to colour specific bars and their corresponding intersect diagram beneath? 

something like example 1 here:
https://cran.r-project.org/web/packages/UpSetR/vignettes/attribute.plots.html

I feel this is an important communication device as generally sets are used to draw attention to a particular group. Numbers above the columns would be great to but I'd consider that a luxury :)

### PR DESCRIPTION
**Pull request by jhfoxliu**
Changes:
1. Enable boundary control
2. Enable control the colors of specific rows/columns in the matrix
3. Enable control the colors of specific bar in intersection barplot and total barplot (catplot was not changed)
4. Enable seperately control the color and width of vlines in the matrix
5. Enable turn on/off the grid lines in the barplots

An example file was provided.

Fixes #46

### CODE REVIEW

**Comment by jnothman** [comment]
Thanks for the example. Let's leave "boundary control" (I think you mean "threshold" rather than "boundary") out of this PR.

I'd also be happier if grid lines were separated into a separate PR, so that this can focus on colour.

**Comment by jnothman** [comment]
And thank you for contributing!

Unfortunately there are test failures in `test_process_data_frame` and your code needs to comply with PEP8.

**Comment by sysuliujh** [comment]
Problems solved. I update the key words augments for more flexible plotting (see the updated example). Threshold settings were removed since in some cases all false indexes cannot be cleaned. For grid lines, I don't know to what extent arguments should be provided in a single interface. For me, I know how to access the ax in UpSet object, but it's a bit hard for beginers.

**Comment by jnothman** [comment]
Looking at the example, this provides much more flexibility than I would like, making it harder for users to learn the library. Can you please justify each new parameter?

**Comment by jnothman** [comment]
I might much rather a solution specifically to #46 than something which tries to be flexible in ways the user is unlikely going to need...

**Comment by sysuliujh** [comment]
Let's focus on colors and bar size in this branch, other arguments were omitted now. Docs under UpSet Class were updated. 
I think we can open another pull request if other key words (i.e. totals_kws) should be appended.

**Comment by jnothman** [comment]
Maybe we should have a `apply_theme` method rather than putting this all into a bloated constructor??

**Comment by jhfoxliu** [comment]
> Maybe we should have a `apply_theme` method rather than putting this all into a bloated constructor??

Hi Jnothman, I owe you a thank because I sucessfully have my article published with the upsetplot! I am busy with my projects and my post-doc application, so I am afraid that I don't have the time to continue in the most recent. 

Personally speaking, I think upsetplot is something complicated, especially when I tried to build it myself from the bottom. So it is  better to avoid users to modify the code theirselves for decorations. And of course putting all the options in the parentheses makes the users stunned, too. Maybe we can hide the advanced options in the manual and have a theme option with some default settings. Then you can just exhibit a figure and point out which parameter controls which feature, like this:
v2-e7d15ff17a3574e0083b8d65ad5a88df_720w

**Comment by jnothman** [comment]
Hi @akshay2000, currently there is a single color setting ([`facecolor`](https://github.com/jnothman/UpSetPlot/blob/38e9f8f85fa0db052d8556a3a4a6bf6911b628c9/upsetplot/plotting.py#L293-L294)), and another two colors that are hardcoded but should not be (a pull request patching this is welcome): https://github.com/jnothman/UpSetPlot/blob/38e9f8f85fa0db052d8556a3a4a6bf6911b628c9/upsetplot/plotting.py#L634 and https://github.com/jnothman/UpSetPlot/blob/38e9f8f85fa0db052d8556a3a4a6bf6911b628c9/upsetplot/plotting.py#L505

All other colors are going to come from your matplotlib [style sheet](https://matplotlib.org/stable/tutorials/introductory/customizing.html).

Perhaps there are more appropriate ways to ensure that the default face color and other colors match the background. For example, facecolor could default to white if the background is dark, and the shading could default to that same color with alpha 4% for shading and 34% for the circles...

I do intend to support an API for specifying intersections to highlight, but I don't consider that to be theming.

**Comment by jnothman** [comment]
I had a hack at it, actually: https://github.com/jnothman/UpSetPlot/pull/new/rel-colors

**Pull request closed without merging**
