### PR TITLE
Documentation for data format

### PR DESCRIPTION
**Pull request by SichongP**
A draft documentation for data format. Some html tables rendered fine with sphinx but seems weird on github. This is my first time working with rst files so let me know if there are any errors. Thanks :)

### CODE REVIEW

**Comment by jnothman** [comment]
This is looking like a good start, though I am not particularly happy with all the HTML tables in there. I think I'd be happier using nbsphinx so that you can just implement the doc in a Jupyter notebook. WDYT?

**Comment by jnothman** [comment]
Please also add the data format guide to the toctree in `index.rst`.

**Comment by jnothman** [comment]
The current version here is focused on "here's a representation and here's what it means and how to use it". Do you think it would be more informative if it was structured around different use cases (as listed in #57) and for each use case would give some examples of how you may already have the data represented, describing how to transform it for use in upsetplot?

**Comment by SichongP** [comment]
> This is looking like a good start, though I am not particularly happy with all the HTML tables in there. I think I'd be happier using nbsphinx so that you can just implement the doc in a Jupyter notebook. WDYT?

I actually wrote it in notebook so yes nbsphinx sounds like a great idea!

**Comment by SichongP** [comment]
> The current version here is focused on "here's a representation and here's what it means and how to use it". Do you think it would be more informative if it was structured around different use cases (as listed in #57) and for each use case would give some examples of how you may already have the data represented, describing how to transform it for use in upsetplot?

I thought that it'd be helpful to start by explaining the data structures required for input in more detail so people can reformat their data (which may come in a wide variety) to this format.

I do think that a few examples of different use cases can be very helpful. So here are my understandings of your points:

- Representing counts only  

Is `movies` dataset good enough for this use case? We can demonstrate how to use `subset_size='count'` with a DataFrame as well as how to group data, filter by counts, and plot with `sum_over`  
- Representing data elements and their associated sets  

Are you talking about something like this?
```
[
    ['cat0', 'cat1'],
    ['cat0', 'cat2'],
    ['cat1']
]
```
I find it difficult to see a use case with this kind of data format... Do you have an example I can start with?

- Representing additional attributes for each data element

Would this be the [Boston data](https://upsetplot.readthedocs.io/en/stable/auto_examples/plot_boston.html) example in Doc? I think that is by itself a great example and could just be used here.

**Comment by jnothman** [comment]
> I actually wrote it in notebook so yes nbsphinx sounds like a great idea!

Are you able to make this change?

**Comment by SichongP** [comment]
> I actually wrote it in notebook so yes nbsphinx sounds like a great idea!
> Are you able to make this change?

Okay hopefully it should be working with my ipynb file now.

**Comment by jnothman** [comment]
Thank you @SichongP! sorry for the delay!

**Pull request merged**
