### PR TITLE
Allow arbitrary ordering

### PR DESCRIPTION
**Pull request by outlace**
Two minor changes to allow the data to be plotted in the order the data is originally supplied. Before this patch, you can only have the data ordered by degree or cardinality.

### CODE REVIEW

**Comment by jnothman** [comment]
Why closed?

**Comment by outlace** [comment]
I need to fix the test so it passes the test suite

There is a test to make it fail if `None` is passed as argument to order

**Comment by jnothman** [comment]
Yes, but if the spec changes, so can the test :)

**Comment by jnothman** [comment]
You can add new commits in this PR branch, if you reopen the PR.

**Pull request closed without merging**
