### PR TITLE
adding intersections ylabel

### PR DESCRIPTION
**Pull request by wdecoster**
This commit fixes https://github.com/jnothman/UpSetPlot/issues/53

### CODE REVIEW

**Comment by jnothman** [comment]
Thanks for the PR. Does this fix the problem for you? I still can't see a ylabel in the documentation examples after this change.

**Comment by wdecoster** [comment]
It seems to work on my system:

image

(I have my branch of upsetplot installed using `pip install -e .`)

**Comment by jnothman** [comment]
For some reason it's not rendering in the docs atm, but I confirm that when running the examples by themselves, it works.

**Comment by jnothman** [comment]
Thanks!

**Comment by jnothman** [comment]
Yeah, it's still not showing at https://upsetplot.readthedocs.io/en/latest/ (for build 9102499 after this PR was merged). I'll reopen the issue. Thanks for trying!!

**Pull request merged**
