### PR TITLE
Manually control the width of "totals" plot

### PR DESCRIPTION
**Pull request by rraadd88**
Hi @jnothman ,
I wanted to manually set the width of "totals" (sub)plot because the defaults were for some reason not working for me. This might have happened because my text elements had new line characters ('\n') and latex symbols. But I am not sure. 
So, I modified the code a little bit and turned out it didn't break the package(!) and the manual settings are working well. I wonder if this could be any useful for adding new control-options etc.

### CODE REVIEW

**Comment by jnothman** [comment]
I think this defies the totals_plot_elements parameter configured by the user?

**Comment by jnothman** [comment]
Can you give me some input to test the bad case with?

**Comment by jnothman** [comment]
Maybe I can find another solution then

**Comment by rraadd88** [comment]
Hi @jnothman ,
Sorry for the late reply. To figure out what was bad in that case, I tried out text elements with and without latex or new-line characters. Turns out the issue was not due to them.
It seems that when the number of categories goes beyond 3, the spacing of names of the categories with respect to the totals subplot and intersection subplot increases exponentially. That's why I had to manually adjust these spacings. It is possible to do this by adjusting the width of totals subplot, as I did in my pull request.

Here's an example:
```
from upsetplot import generate_counts
from upsetplot import plot
example = generate_counts(n_categories=7)
plot(example) 
```
Output:
image

**Comment by jnothman** [comment]
Just from the diagram, this might be a duplicate of the issue in #106

**Comment by rraadd88** [comment]
Ah, ok. So please feel free to delete this pull request. 
Now that I know the inner workings of the upsetplot a little bit, I will see if I can contribute in fixing this issue in some other way. 👍

**Pull request closed without merging**
